export const PACKS_LIST = [
  'Turtle Pack',
  'Puppy Pack',
  'Star Pack',
  'Golden Pack',
  'Unicorn Pack',
  'Custom Pack',
] as const;

export const TIERS_LIST = [1, 2, 3, 4, 5, 6] as const;

export const ABILITY_TRIGGERS_LIST = [
  '',
  'Buy',
  'Buy Friend',
  'Buy Food',
  'Sell',
  'Hurt',
  'Hurt & Sell',
  'Faint',
  'Faint & Sell',
  'Level Up',
  'Friend Summoned',
  'Summoned',
  'Start Of Battle',
  'Start Of Turn',
  'End Turn',
  'Knock Out',
  'Before Attack',
  'After Attack',
  'Eats Food',
  'Friendly Eats Food',
  'Friendly Gained Perk',
  'Friendly Gained Ailment',
  'Friendly Attacked',
  'Friendly Level-Up',
  'Friend Ahead Attacks',
  'Friend Ahead Hurt',
  'Friend Ahead Faints',
  'Friend Faints',
  'Friend Level-Up',
  'Friend Hurt',
  'Friend Sold',
  'Friend Jumped',
  'Roll',
  'Roll 4 Times',
  'Shop Tier Upgraded',
  'Gains Mana',
  'Enemy Summoned or Pushed', // nrk
  'Empty Front Space',
] as const;

export const TAGS_LIST = [
  'Summon',
  'Hurt',
  'Food',
  'Guard',
  'Perks',
  'Ailment',
  'Cycle',
  'Rolling',
  'Level-Up',
  'Gold',
  'Toys',
  'Strawberry',
  'Trumpets',
  'Mana',
  'Faint',
  'Buffs',
  'Disruption',
] as const;

export const REQUIREMENT_SPECIFIC_KEYS = [
  'tier1',
  'tier2',
  'tier3',
  'tier4',
  'tier5',
  'tier6',
  'healthLow',
  'healthMedium',
  'healthHigh',
  'attackLow',
  'attackMedium',
  'attackHigh',
] as const;

export const REQUIREMENT_GENERIC_KEYS = [
  'turtlePack',
  'puppyPack',
  'starPack',
  'goldenPack',
  'unicornPack',
  'customPack',
  'noAbility',
  'buy',
  'buyFriend',
  'buyFood',
  'sell',
  'hurt',
  'faint',
  'levelUp',
  'friendSummoned',
  'summoned',
  'startOfBattle',
  'startOfTurn',
  'endTurn',
  'knockOut',
  'beforeAttack',
  'afterAttack',
  'eatsFood',
  'friendlyEatsFood',
  'friendlyGained',
  'friendlyAttacked',
  'friendlyLevelUp',
  'friendAhead',
  'friendLevelUp',
  'friendHurt',
  'friendFaints',
  'friendSold',
  'friendJumped',
  'roll',
  'shopTierUpgraded',
  'gainsMana',
  'emptyFrontSpace',
] as const;
