export const PACKS_LIST = [
  'Turtle Pack',
  'Puppy Pack',
  'Star Pack',
  'Golden Pack',
  'Unicorn Pack',
  'Custom Pack',
] as const;

export const TIERS_LIST = [1, 2, 3, 4, 5, 6, 'Token'] as const;

export const ABILITY_TRIGGERS_LIST = [
  '',
  'Buy',
  'Buy Friend',
  'Buy Food',
  'Sell',
  'Hurt',
  'Hurt & Sell',
  'Faint',
  'Level Up',
  'Friend Summoned',
  'Summoned',
  'Start Of Battle',
  'Start Of Turn',
  'End Turn',
  'Knock Out',
  'Before Attack',
  'After Attack',
  'Eats Food',
  'Friendly Eats Food',
  'Friendly Gained Perk',
  'Friendly Gained Ailment',
  'Friend Ahead Attacks',
  'Friend Ahead Hurt',
  'Friend Ahead Faints',
  'Friend Level-Up',
  'Friend Hurt',
  'Roll',
  'Shop Tier Upgraded',
  'Gains Mana',
] as const;

export const TAGS_LIST = [
  'Summon',
  'Hurt',
  'Food',
  'Guard',
  'Perks',
  'Ailment',
  'Cycle',
  'Rolling',
  'Level-Up',
  'Gold',
  'Toys',
  'Strawberry',
  'Trumpets',
  'Mana',
  'Faint',
  'Buffs',
  'Disruption',
] as const;
