import { Pet } from './types';

// 450 pets lol
export const PETS_LIST: Pet[] = [
  //
  // TIER 1
  //
  {
    name: 'Ant',
    imageSrc: 'https://superautopets.wiki.gg/images/5/56/Ant.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tag: ['Faint'],
  },
  {
    name: 'Beaver',
    imageSrc: 'https://superautopets.wiki.gg/images/2/26/Beaver.png',
    pack: ['Turtle Pack', 'Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Cycle'],
  },
  {
    name: 'Cricket',
    imageSrc: 'https://superautopets.wiki.gg/images/3/3d/Cricket.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Faint',
    tag: ['Summon'],
  },
  {
    name: 'Duck',
    imageSrc: 'https://superautopets.wiki.gg/images/3/38/Duck.png',
    pack: ['Turtle Pack', 'Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tag: ['Buffs'],
  },
  {
    name: 'Fish',
    imageSrc: 'https://superautopets.wiki.gg/images/f/fb/Fish.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Level Up',
    tag: ['Level-Up'],
  },
  {
    name: 'Horse',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c3/Horse.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Friend Summoned',
    tag: ['Summon'],
  },
  {
    name: 'Mosquito',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8a/Mosquito.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: ['Disruption'],
  },
  {
    name: 'Otter',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9f/Otter.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Buy',
    tag: ['Cycle'],
  },
  {
    name: 'Pig',
    imageSrc: 'https://superautopets.wiki.gg/images/3/30/Pig.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 4,
    health: 1,
    abilityTrigger: 'Sell',
    tag: ['Gold', 'Cycle'],
  },
  {
    name: 'Pigeon',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9e/Pigeon.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Sell',
    tag: ['Food'],
  },
  {
    name: 'Chinchilla',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e8/Chinchilla.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Gold', 'Cycle'],
  },
  {
    name: 'Moth',
    imageSrc: 'https://superautopets.wiki.gg/images/0/09/Moth.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tag: [],
  },
  {
    name: 'Marmoset',
    imageSrc: 'https://superautopets.wiki.gg/images/f/ff/Marmoset.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tag: ['Cycle'],
  },
  {
    name: 'Budgie',
    imageSrc: 'https://superautopets.wiki.gg/images/5/59/Budgie.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Perks'],
  },
  {
    name: 'Farmer Mouse',
    imageSrc: 'https://superautopets.wiki.gg/images/e/eb/Farmer_Mouse.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tag: ['Food'],
  },
  {
    name: 'Frilled Dragon',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8d/Frilled_Dragon.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 1,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Faint'],
  },
  {
    name: 'Weevil',
    imageSrc: 'https://superautopets.wiki.gg/images/8/81/Weevil.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Friendly Eats Food',
    tag: ['Food'],
  },
  {
    name: 'Beetle',
    imageSrc: 'https://superautopets.wiki.gg/images/6/60/Beetle.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: ['Perks'],
  },
  {
    name: 'Bluebird',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9b/Bluebird.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'End Turn',
    tag: ['Buffs'],
  },
  {
    name: 'Chipmunk',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9e/Chipmunk.png',
    pack: ['Golden Pack', 'Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Perks'],
  },
  {
    name: 'Ferret',
    imageSrc: 'https://superautopets.wiki.gg/images/0/09/Ferret.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Buy',
    tag: ['Toys'],
  },
  {
    name: 'Gecko',
    imageSrc: 'https://superautopets.wiki.gg/images/1/16/Gecko.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Toys'],
  },
  {
    name: 'Ladybug',
    imageSrc: 'https://superautopets.wiki.gg/images/3/38/Ladybug.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Friendly Gained Perk',
    tag: ['Perks'],
  },
  {
    name: 'Chihuahua',
    imageSrc: 'https://superautopets.wiki.gg/images/4/48/Chihuahua.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 4,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Disruption'],
  },
  {
    name: 'Cockroach',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d9/Cockroach.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 1,
    health: 1,
    abilityTrigger: 'Faint',
    tag: ['Level-Up', 'Summon'],
  },
  {
    name: 'Duckling',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b6/Duckling.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Buffs'],
  },
  {
    name: 'Firefly',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d7/Firefly.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tag: ['Hurt'],
  },
  {
    name: 'Frog',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e6/Frog.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tag: [],
  },
  {
    name: 'Gibbon',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b0/Gibbon.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Shop Tier Upgraded',
    tag: ['Buffs'],
  },
  {
    name: 'Hummingbird',
    imageSrc: 'https://superautopets.wiki.gg/images/2/23/Hummingbird.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: ['Strawberry', 'Perks'],
  },
  {
    name: 'Kiwi',
    imageSrc: 'https://superautopets.wiki.gg/images/e/ea/Kiwi.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'Hurt & Sell',
    tag: ['Strawberry'],
  },
  {
    name: 'Mouse',
    imageSrc: 'https://superautopets.wiki.gg/images/5/5c/Mouse.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Food'],
  },
  {
    name: 'Pheasant',
    imageSrc: 'https://superautopets.wiki.gg/images/f/f1/Pheasant.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Friend Summoned',
    tag: ['Strawberry', 'Perks'],
  },
  {
    name: 'Pillbug',
    imageSrc: 'https://superautopets.wiki.gg/images/a/ab/Pillbug.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Faint'],
  },
  {
    name: 'Termite',
    imageSrc: 'https://superautopets.wiki.gg/images/1/19/Termite.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'Start Of Turn',
    tag: [],
  },
  {
    name: 'Bulldog',
    imageSrc: 'https://superautopets.wiki.gg/images/0/07/Bulldog.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'After Attack',
    tag: [],
  },
  {
    name: 'Cone Snail',
    imageSrc: 'https://superautopets.wiki.gg/images/6/66/Cone_Snail.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: [],
  },
  {
    name: 'Goose',
    imageSrc: 'https://superautopets.wiki.gg/images/d/dd/Goose.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: [],
  },
  {
    name: 'Groundhog',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d5/Groundhog.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Faint',
    tag: ['Trumpets'],
  },
  {
    name: 'Magpie',
    imageSrc: 'https://superautopets.wiki.gg/images/1/17/Magpie.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'End Turn',
    tag: ['Gold'],
  },
  {
    name: 'Opossum',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b1/Opossum.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tag: ['Buffs'],
  },
  {
    name: 'Pied Tamarin',
    imageSrc: 'https://superautopets.wiki.gg/images/2/29/Pied_Tamarin.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Faint',
    tag: ['Trumpets'],
  },
  {
    name: 'Silkmoth',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c9/Silkmoth.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Friend Ahead Hurt',
    tag: [],
  },
  {
    name: '???',
    imageSrc: 'https://superautopets.wiki.gg/images/c/cf/%3F%3F%3F.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'End Turn',
    tag: ['Ailment'],
  },
  {
    name: 'Alchemedes',
    imageSrc: 'https://superautopets.wiki.gg/images/1/11/Alchemedes.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: ['Mana'],
  },
  {
    name: 'Baku',
    imageSrc: 'https://superautopets.wiki.gg/images/b/bd/Baku.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'End Turn',
    tag: ['Ailment'],
  },
  {
    name: 'Barghest',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8f/Barghest.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tag: ['Ailment'],
  },
  {
    name: 'Basilisk',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b1/Basilisk.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Disruption'],
  },
  {
    name: 'Bunyip',
    imageSrc: 'https://superautopets.wiki.gg/images/3/32/Bunyip.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Rolling'],
  },
  {
    name: 'Cuddle Toad',
    imageSrc: 'https://superautopets.wiki.gg/images/7/70/Cuddle_Toad.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tag: ['Toys'],
  },
  {
    name: 'Murmel',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e1/Murmel.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Friend Level-Up',
    tag: ['Level-Up'],
  },
  {
    name: 'Pengobble',
    imageSrc: 'https://superautopets.wiki.gg/images/7/7a/Pengobble.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Gains Mana',
    tag: ['Mana'],
  },
  {
    name: 'Sneaky Egg',
    imageSrc: 'https://superautopets.wiki.gg/images/9/91/Sneaky_Egg.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tag: ['Guard'],
  },
  {
    name: 'Tsuchinoko',
    imageSrc: 'https://superautopets.wiki.gg/images/f/fd/Tsuchinoko.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Level-Up', 'Guard'],
  },
  {
    name: 'Pygmy Seahorse',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c4/Pygmy_Seahorse.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tag: ['Cycle'],
  },
  {
    name: 'Silverfish',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b9/Silverfish.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Gold'],
  },
  {
    name: 'Umbrella Bird',
    imageSrc: 'https://superautopets.wiki.gg/images/2/2b/Long_Wattled_Umbrella_Bird.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'End Turn',
    tag: ['Ailment'],
  },
  {
    name: 'Nudibranch',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c6/Nudibranch.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: [],
  },
  //
  // --- TIER 2 ---
  //
] as const;

/*
{
  name: '',
  imageSrc: '',
  pack: [''],
  tier: 1,
  attack: 0,
  health: 0,
  abilityTrigger: '',
  tag: ['']
},

*/

type PetsName = (typeof PETS_LIST)[number]['name'];
type PetsMapType = Record<PetsName, Pet>;

export const PETS_MAP = PETS_LIST.reduce((acc, pet) => {
  acc[pet.name] = pet;
  return acc;
}, {} as PetsMapType);
