import { Pet } from './types';

// 450 pets lol
export const PETS_LIST: Pet[] = [
  //
  // TIER 1
  //
  {
    name: 'Ant',
    imageSrc: 'https://superautopets.wiki.gg/images/5/56/Ant.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Faint'],
  },
  {
    name: 'Beaver',
    imageSrc: 'https://superautopets.wiki.gg/images/2/26/Beaver.png',
    pack: ['Turtle Pack', 'Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Cycle'],
  },
  {
    name: 'Cricket',
    imageSrc: 'https://superautopets.wiki.gg/images/3/3d/Cricket.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Duck',
    imageSrc: 'https://superautopets.wiki.gg/images/3/38/Duck.png',
    pack: ['Turtle Pack', 'Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tags: ['Buffs'],
  },
  {
    name: 'Fish',
    imageSrc: 'https://superautopets.wiki.gg/images/f/fb/Fish.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Level Up',
    tags: ['Level-Up'],
  },
  {
    name: 'Horse',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c3/Horse.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Friend Summoned',
    tags: ['Summon'],
  },
  {
    name: 'Mosquito',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8a/Mosquito.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  {
    name: 'Otter',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9f/Otter.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Buy',
    tags: ['Cycle'],
  },
  {
    name: 'Pig',
    imageSrc: 'https://superautopets.wiki.gg/images/3/30/Pig.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 4,
    health: 1,
    abilityTrigger: 'Sell',
    tags: ['Gold', 'Cycle'],
  },
  {
    name: 'Pigeon',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9e/Pigeon.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Sell',
    tags: ['Food'],
  },
  {
    name: 'Chinchilla',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e8/Chinchilla.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Gold', 'Cycle'],
  },
  {
    name: 'Moth',
    imageSrc: 'https://superautopets.wiki.gg/images/0/09/Moth.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Marmoset',
    imageSrc: 'https://superautopets.wiki.gg/images/f/ff/Marmoset.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tags: ['Cycle'],
  },
  {
    name: 'Budgie',
    imageSrc: 'https://superautopets.wiki.gg/images/5/59/Budgie.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Perks'],
  },
  {
    name: 'Farmer Mouse',
    imageSrc: 'https://superautopets.wiki.gg/images/e/eb/Farmer_Mouse.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Food'],
  },
  {
    name: 'Frilled Dragon',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8d/Frilled_Dragon.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 1,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Faint'],
  },
  {
    name: 'Weevil',
    imageSrc: 'https://superautopets.wiki.gg/images/8/81/Weevil.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Friendly Eats Food',
    tags: ['Food'],
  },
  {
    name: 'Beetle',
    imageSrc: 'https://superautopets.wiki.gg/images/6/60/Beetle.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Perks'],
  },
  {
    name: 'Bluebird',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9b/Bluebird.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'End Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Chipmunk',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9e/Chipmunk.png',
    pack: ['Golden Pack', 'Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Perks'],
  },
  {
    name: 'Ferret',
    imageSrc: 'https://superautopets.wiki.gg/images/0/09/Ferret.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Buy',
    tags: ['Toys'],
  },
  {
    name: 'Gecko',
    imageSrc: 'https://superautopets.wiki.gg/images/1/16/Gecko.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Toys'],
  },
  {
    name: 'Ladybug',
    imageSrc: 'https://superautopets.wiki.gg/images/3/38/Ladybug.png',
    pack: ['Puppy Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Friendly Gained Perk',
    tags: ['Perks'],
  },
  {
    name: 'Chihuahua',
    imageSrc: 'https://superautopets.wiki.gg/images/4/48/Chihuahua.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 4,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  {
    name: 'Cockroach',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d9/Cockroach.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 1,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Level-Up', 'Summon'],
  },
  {
    name: 'Duckling',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b6/Duckling.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Buffs'],
  },
  {
    name: 'Firefly',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d7/Firefly.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Hurt'],
  },
  {
    name: 'Frog',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e6/Frog.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tags: [],
  },
  {
    name: 'Gibbon',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b0/Gibbon.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Shop Tier Upgraded',
    tags: ['Buffs'],
  },
  {
    name: 'Hummingbird',
    imageSrc: 'https://superautopets.wiki.gg/images/2/23/Hummingbird.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Strawberry', 'Perks'],
  },
  {
    name: 'Kiwi',
    imageSrc: 'https://superautopets.wiki.gg/images/e/ea/Kiwi.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'Hurt & Sell',
    tags: ['Strawberry'],
  },
  {
    name: 'Mouse',
    imageSrc: 'https://superautopets.wiki.gg/images/5/5c/Mouse.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Food'],
  },
  {
    name: 'Pheasant',
    imageSrc: 'https://superautopets.wiki.gg/images/f/f1/Pheasant.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Friend Summoned',
    tags: ['Strawberry', 'Perks'],
  },
  {
    name: 'Pillbug',
    imageSrc: 'https://superautopets.wiki.gg/images/a/ab/Pillbug.png',
    pack: ['Star Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Faint'],
  },
  {
    name: 'Termite',
    imageSrc: 'https://superautopets.wiki.gg/images/1/19/Termite.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'Start Of Turn',
    tags: [],
  },
  {
    name: 'Bulldog',
    imageSrc: 'https://superautopets.wiki.gg/images/0/07/Bulldog.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'After Attack',
    tags: [],
  },
  {
    name: 'Cone Snail',
    imageSrc: 'https://superautopets.wiki.gg/images/6/66/Cone_Snail.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Goose',
    imageSrc: 'https://superautopets.wiki.gg/images/d/dd/Goose.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Groundhog',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d5/Groundhog.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Magpie',
    imageSrc: 'https://superautopets.wiki.gg/images/1/17/Magpie.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'End Turn',
    tags: ['Gold'],
  },
  {
    name: 'Opossum',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b1/Opossum.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tags: ['Buffs'],
  },
  {
    name: 'Pied Tamarin',
    imageSrc: 'https://superautopets.wiki.gg/images/2/29/Pied_Tamarin.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 1,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Silkmoth',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c9/Silkmoth.png',
    pack: ['Golden Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Friend Ahead Hurt',
    tags: [],
  },
  {
    name: '???',
    imageSrc: 'https://superautopets.wiki.gg/images/c/cf/%3F%3F%3F.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'End Turn',
    tags: ['Ailment'],
  },
  {
    name: 'Alchemedes',
    imageSrc: 'https://superautopets.wiki.gg/images/1/11/Alchemedes.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Mana'],
  },
  {
    name: 'Baku',
    imageSrc: 'https://superautopets.wiki.gg/images/b/bd/Baku.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 1,
    health: 4,
    abilityTrigger: 'End Turn',
    tags: ['Ailment'],
  },
  {
    name: 'Barghest',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8f/Barghest.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Ailment'],
  },
  {
    name: 'Basilisk',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b1/Basilisk.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  {
    name: 'Bunyip',
    imageSrc: 'https://superautopets.wiki.gg/images/3/32/Bunyip.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Rolling'],
  },
  {
    name: 'Cuddle Toad',
    imageSrc: 'https://superautopets.wiki.gg/images/7/70/Cuddle_Toad.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tags: ['Toys'],
  },
  {
    name: 'Murmel',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e1/Murmel.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Friend Level-Up',
    tags: ['Level-Up'],
  },
  {
    name: 'Pengobble',
    imageSrc: 'https://superautopets.wiki.gg/images/7/7a/Pengobble.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Gains Mana',
    tags: ['Mana'],
  },
  {
    name: 'Sneaky Egg',
    imageSrc: 'https://superautopets.wiki.gg/images/9/91/Sneaky_Egg.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tags: ['Guard'],
  },
  {
    name: 'Tsuchinoko',
    imageSrc: 'https://superautopets.wiki.gg/images/f/fd/Tsuchinoko.png',
    pack: ['Unicorn Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Level-Up', 'Guard'],
  },
  {
    name: 'Pygmy Seahorse',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c4/Pygmy_Seahorse.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Cycle'],
  },
  {
    name: 'Silverfish',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b9/Silverfish.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Gold'],
  },
  {
    name: 'Umbrella Bird',
    imageSrc: 'https://superautopets.wiki.gg/images/2/2b/Long_Wattled_Umbrella_Bird.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'End Turn',
    tags: ['Ailment'],
  },
  {
    name: 'Nudibranch',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c6/Nudibranch.png',
    pack: ['Custom Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  //
  // --- TIER 2 ---
  //
  {
    name: 'Crab',
    imageSrc: 'https://superautopets.wiki.gg/images/6/63/Crab.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 4,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Flamingo',
    imageSrc: 'https://superautopets.wiki.gg/images/0/0b/Flamingo.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 3,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Faint'],
  },
  {
    name: 'Hedgehog',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c4/Hedgehog.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 4,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Hurt'],
  },
  {
    name: 'Kangaroo',
    imageSrc: 'https://superautopets.wiki.gg/images/5/56/Kangaroo.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 1,
    health: 2,
    abilityTrigger: 'Friend Ahead Attacks',
    tags: ['Guard'],
  },
  {
    name: 'Peacock',
    imageSrc: 'https://superautopets.wiki.gg/images/6/61/Peacock.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 2,
    health: 5,
    abilityTrigger: 'Hurt',
    tags: ['Hurt'],
  },
  {
    name: 'Rat',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8b/Rat.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 3,
    health: 6,
    abilityTrigger: 'Faint',
    tags: ['Hurt'],
  },
  {
    name: 'Snail',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d2/Snail.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'End Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Spider',
    imageSrc: 'https://superautopets.wiki.gg/images/8/84/Spider.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 1,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Swan',
    imageSrc: 'https://superautopets.wiki.gg/images/8/87/Swan.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Turn',
    tags: ['Gold'],
  },
  {
    name: 'Worm',
    imageSrc: 'https://superautopets.wiki.gg/images/5/52/Worm.png',
    pack: ['Turtle Pack'],
    tier: 2,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Turn',
    tags: ['Food'],
  },
  {
    name: 'Frigatebird',
    imageSrc: 'https://superautopets.wiki.gg/images/e/ed/Frigatebird.png',
    pack: ['Puppy Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 5,
    abilityTrigger: 'Friendly Gained Ailment',
    tags: ['Ailment'],
  },
  {
    name: 'Shrimp',
    imageSrc: 'https://superautopets.wiki.gg/images/9/91/Shrimp.png',
    pack: ['Puppy Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'Friend Sold',
    tags: ['Cycle'],
  },
  {
    name: 'Toucan',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e2/Toucan.png',
    pack: ['Puppy Pack', 'Custom Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Perks'],
  },
  {
    name: 'Albino Squirrel',
    imageSrc: 'https://superautopets.wiki.gg/images/0/0c/Albino_Squirrel.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Food'],
  },
  {
    name: 'Dung Beetle',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b4/Dung_Beetle.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 1,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Disruption', 'Food'],
  },
  {
    name: 'Farmer Chicken',
    imageSrc: 'https://superautopets.wiki.gg/images/1/1f/Farmer_Chicken.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Food'],
  },
  {
    name: 'Mink',
    imageSrc: 'https://superautopets.wiki.gg/images/2/2f/Mink.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Perks'],
  },
  {
    name: 'Vervet',
    imageSrc: 'https://superautopets.wiki.gg/images/4/4b/Vervet.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 1,
    health: 3,
    abilityTrigger: 'Buy',
    tags: ['Toys'],
  },
  {
    name: 'Wombat',
    imageSrc: 'https://superautopets.wiki.gg/images/a/a2/Wombat.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'Before Attack',
    tags: [],
  },
  {
    name: 'Bat',
    imageSrc: 'https://superautopets.wiki.gg/images/a/ad/Bat.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Ailment'],
  },
  {
    name: 'Beluga Sturgeon',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c7/Beluga_Sturgeon.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Dromedary',
    imageSrc: 'https://superautopets.wiki.gg/images/6/6a/Dromedary.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 2,
    health: 4,
    abilityTrigger: 'Start Of Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Lemur',
    imageSrc: 'https://superautopets.wiki.gg/images/1/1f/Lemur.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'Buy',
    tags: ['Toys'],
  },
  {
    name: 'Mandrill',
    imageSrc: 'https://superautopets.wiki.gg/images/f/f1/Mandrill.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 3,
    health: 4,
    abilityTrigger: 'Faint',
    tags: ['Toys'],
  },
  {
    name: 'Robin',
    imageSrc: 'https://superautopets.wiki.gg/images/1/1b/Robin.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Cycle'],
  },
  {
    name: 'Tabby Cat',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b3/Tabby_Cat.png',
    pack: ['Puppy Pack'],
    tier: 2,
    attack: 4,
    health: 2,
    abilityTrigger: 'Friendly Gained Perk',
    tags: ['Perks'],
  },
  {
    name: 'Atlantic Puffin',
    imageSrc: 'https://superautopets.wiki.gg/images/7/70/Atlantic_Puffin.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 4,
    health: 3,
    abilityTrigger: 'Friendly Attacked',
    tags: ['Strawberry'],
  },
  {
    name: 'Bass',
    imageSrc: 'https://superautopets.wiki.gg/images/b/bd/Bass.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint & Sell',
    tags: ['Level-Up'],
  },
  {
    name: 'Dove',
    imageSrc: 'https://superautopets.wiki.gg/images/5/5d/Dove.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 1,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Strawberry'],
  },
  {
    name: 'Dumbo Octopus',
    imageSrc: 'https://superautopets.wiki.gg/images/1/1b/Dumbo_Octopus.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 2,
    health: 5,
    abilityTrigger: 'Roll 4 Times',
    tags: ['Rolling'],
  },
  {
    name: 'Guinea Pig',
    imageSrc: 'https://superautopets.wiki.gg/images/1/19/Guinea_Pig.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Buy',
    tags: ['Level-Up'],
  },
  {
    name: 'Iguana',
    imageSrc: 'https://superautopets.wiki.gg/images/a/af/Iguana.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 2,
    health: 4,
    abilityTrigger: 'Enemy Summoned or Pushed',
    tags: ['Disruption'],
  },
  {
    name: 'Jellyfish',
    imageSrc: 'https://superautopets.wiki.gg/images/2/22/Jellyfish.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Friend Level-Up',
    tags: ['Level-Up'],
  },
  {
    name: 'Koala',
    imageSrc: 'https://superautopets.wiki.gg/images/2/22/Koala.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 3,
    health: 2,
    abilityTrigger: 'Friend Hurt',
    tags: ['Perks'],
  },
  {
    name: 'Panda',
    imageSrc: 'https://superautopets.wiki.gg/images/0/00/Panda.png',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Salamander',
    imageSrc: 'https://superautopets.wiki.gg/images/5/53/Salamander.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 1,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Level-Up'],
  },
  {
    name: 'Seahorse',
    imageSrc: 'https://superautopets.wiki.gg/images/6/6e/Seahorse.png',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  {
    name: 'Shima Enaga',
    imageSrc: 'https://superautopets.wiki.gg/images/5/59/Shima_Enaga_Icon.png',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Friend Faints',
    tags: ['Strawberry'],
  },
  {
    name: 'Stork',
    imageSrc: 'https://superautopets.wiki.gg/images/a/ab/Stork.png',
    pack: ['Star Pack'],
    tier: 2,
    attack: 2,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Yak',
    imageSrc: 'https://superautopets.wiki.gg/images/a/a0/Yak.png',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 2,
    attack: 3,
    health: 5,
    abilityTrigger: 'End Turn',
    tags: ['Hurt'],
  },
  {
    name: 'African Penguin',
    imageSrc: 'https://superautopets.wiki.gg/images/8/80/African_Penguin.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 1,
    health: 3,
    abilityTrigger: 'Buy',
    tags: ['Cycle'],
  },
  {
    name: 'Black Necked Stilt',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c3/Black_Necked_Stilt.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 3,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Desert Rain Frog',
    imageSrc: 'https://superautopets.wiki.gg/images/f/fa/Desert_Rain_Frog_Icon.png',
    pack: ['Golden Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Before Attack',
    tags: ['Trumpets'],
  },
  {
    name: 'Door Head Ant',
    imageSrc: 'https://superautopets.wiki.gg/images/b/b3/Door_Head_Ant.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'Empty Front Space',
    tags: ['Guard'],
  },
  {
    name: 'Gazelle',
    imageSrc: 'https://superautopets.wiki.gg/images/4/4a/Gazelle.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Start Of Turn',
    tags: ['Gold'],
  },
  {
    name: 'Hercules Beetle',
    imageSrc: 'https://superautopets.wiki.gg/images/5/5a/Hercules_Beetle.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 3,
    health: 4,
    abilityTrigger: 'Sell',
    tags: ['Buffs'],
  },
  {
    name: 'Honduran White Bat',
    imageSrc: 'https://superautopets.wiki.gg/images/9/96/Honduran_White_Bat_Icon.png',
    pack: ['Golden Pack', 'Custom Pack'],
    tier: 2,
    attack: 1,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Trumpets'],
  },
  {
    name: 'Lizard',
    imageSrc: 'https://superautopets.wiki.gg/images/4/4d/Lizard.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 1,
    health: 3,
    abilityTrigger: 'Hurt',
    tags: ['Summon'],
  },
  {
    name: 'Sea Turtle',
    imageSrc: 'https://superautopets.wiki.gg/images/f/f0/Sea_Turtle.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 2,
    health: 5,
    abilityTrigger: 'Friend Summoned',
    tags: ['Summon'],
  },
  {
    name: 'Sea Urchin',
    imageSrc: 'https://superautopets.wiki.gg/images/e/e7/Sea_Urchin.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 3,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Faint'],
  },
  {
    name: 'Squid',
    imageSrc: 'https://superautopets.wiki.gg/images/8/81/Squid.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 5,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Stoat',
    imageSrc: 'https://superautopets.wiki.gg/images/f/f6/Stoat.png',
    pack: ['Golden Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'Sell',
    tags: ['Cycle'],
  },
  {
    name: 'Bigfoot',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9c/Bigfoot.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Rolling'],
  },
  {
    name: 'Chupacabra',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c7/Chupacabra.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 2,
    attack: 4,
    health: 2,
    abilityTrigger: 'Knock Out',
    tags: [],
  },
  {
    name: 'Drop Bear',
    imageSrc: 'https://superautopets.wiki.gg/images/a/a8/Drop_Bear.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'Empty Front Space',
    tags: ['Guard', 'Disruption'],
  },
  {
    name: 'Frost Wolf',
    imageSrc: 'https://superautopets.wiki.gg/images/4/46/Frost_Wolf.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 2,
    health: 4,
    abilityTrigger: 'Faint',
    tags: ['Ailment'],
  },
  {
    name: 'Gargoyle',
    imageSrc: 'https://superautopets.wiki.gg/images/4/44/Gargoyle.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Mana'],
  },
  {
    name: 'Ghost Kitten',
    imageSrc: 'https://superautopets.wiki.gg/images/6/6a/Ghost_Kitten.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 3,
    health: 4,
    abilityTrigger: '',
    tags: [],
  },
  {
    name: 'Golden Beetle',
    imageSrc: 'https://superautopets.wiki.gg/images/0/06/Golden_Beetle.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 2,
    attack: 4,
    health: 1,
    abilityTrigger: 'Sell',
    tags: ['Cycle', 'Gold'],
  },
  {
    name: 'Jackalope',
    imageSrc: 'https://superautopets.wiki.gg/images/7/7f/Jackalope.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 1,
    health: 3,
    abilityTrigger: 'Friend Jumped',
    tags: ['Guard'],
  },
  {
    name: 'Mothman',
    imageSrc: 'https://superautopets.wiki.gg/images/0/01/Mothman.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Ailment'],
  },
  {
    name: 'Nightcrawler',
    imageSrc: 'https://superautopets.wiki.gg/images/9/90/Nightcrawler.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 2,
    attack: 1,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Ogopogo',
    imageSrc: 'https://superautopets.wiki.gg/images/7/7f/Ogopogo.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Level-Up'],
  },
  {
    name: 'Sphinx',
    imageSrc: 'https://superautopets.wiki.gg/images/0/0e/Sphinx.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 5,
    abilityTrigger: 'Buy',
    tags: ['Toys'],
  },
  {
    name: 'Thunderbird',
    imageSrc: 'https://superautopets.wiki.gg/images/3/3d/Thunderbird.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 2,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Mana'],
  },
  {
    name: 'Warf',
    imageSrc: 'https://superautopets.wiki.gg/images/d/d0/Warf.png',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'Gains Mana',
    tags: ['Mana'],
  },
  {
    name: 'Wyvern',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c1/Wyvern.png',
    pack: ['Unicorn Pack'],
    tier: 2,
    attack: 3,
    health: 4,
    abilityTrigger: 'Friendly Level-Up',
    tags: ['Level-Up'],
  },
  {
    name: 'Fruit Fly',
    imageSrc: 'https://superautopets.wiki.gg/images/3/31/Fruit_Fly.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 1,
    health: 1,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  {
    name: 'Pink Robin',
    imageSrc: 'https://superautopets.wiki.gg/images/9/92/Pink_Robin.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 3,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Faint'],
  },
  {
    name: 'Giant Squirrel',
    imageSrc: 'https://superautopets.wiki.gg/images/0/0b/Giant_Squirrel_Icon.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 2,
    health: 4,
    abilityTrigger: 'After Attack',
    tags: [],
  },
  {
    name: 'Olm',
    imageSrc: 'https://superautopets.wiki.gg/images/0/0b/Olm_Icon.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 3,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Ailment', 'Rolling'],
  },
  {
    name: 'Tadpole',
    imageSrc: 'https://superautopets.wiki.gg/images/a/a0/Tadpole_Icon.png',
    pack: ['Custom Pack'],
    tier: 2,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Level-Up'],
  },
  //
  // --- TIER 3 ---
  //
  {
    name: 'Badger',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 6,
    health: 3,
    abilityTrigger: 'Faint',
    tags: [],
  },
  {
    name: 'Camel',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 3,
    health: 4,
    abilityTrigger: 'Hurt',
    tags: ['Hurt'],
  },
  {
    name: 'Dodo',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 3,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Dog',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 3,
    health: 2,
    abilityTrigger: 'Friend Summoned',
    tags: ['Summon'],
  },
  {
    name: 'Dolphin',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 4,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  {
    name: 'Elephant',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 3,
    health: 7,
    abilityTrigger: 'After Attack',
    tags: ['Hurt'],
  },
  {
    name: 'Giraffe',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Ox',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'Friend Ahead Faints',
    tags: ['Perks'],
  },
  {
    name: 'Rabbit',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 1,
    health: 2,
    abilityTrigger: 'Friendly Eats Food', // Friendly Ate Food
    tags: ['Food'],
  },
  {
    name: 'Sheep',
    imageSrc: '',
    pack: ['Turtle Pack'],
    tier: 3,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Gold Fish',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 1,
    health: 5,
    abilityTrigger: 'End Turn',
    tags: ['Gold'],
  },
  {
    name: 'Mole',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Perks'],
  },
  {
    name: 'Aardvark',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'Enemy Summoned',
    tags: [],
  },
  {
    name: 'Bear',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 3,
    health: 5,
    abilityTrigger: 'Faint',
    tags: ['Perks'],
  },
  {
    name: 'Emperor Tamarin',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Sell',
    tags: ['Buffs'],
  },
  {
    name: 'Farmer Pig',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 3,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tags: ['Food'],
  },
  {
    name: 'Pony',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 4,
    health: 4,
    abilityTrigger: 'Knock Out',
    tags: ['Food'],
  },
  {
    name: 'Wolverine',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 2,
    health: 6,
    abilityTrigger: 'Hurt',
    tags: [],
  },
  {
    name: 'Quail Chick',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 1,
    health: 1,
    abilityTrigger: 'Eats Food',
    tags: ['Food'],
  },
  {
    name: 'Quetzalcoatlus',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 4,
    health: 6,
    abilityTrigger: 'Faint',
    tags: [],
  },
  {
    name: 'Sarcastic Fringehead',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 4,
    health: 7,
    abilityTrigger: 'Faint',
    tags: ['Hurt'],
  },
  {
    name: 'Sugar Glider',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'Start Of Turn',
    tags: ['Food'],
  },
  {
    name: 'Wasp',
    imageSrc: '',
    pack: [],
    tier: 3,
    attack: 2,
    health: 2,
    abilityTrigger: 'Shop Tier Upgraded',
    tags: [],
  },
  {
    name: 'Flying Squirrel',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Friendly Toy Broke',
    tags: ['Toys'],
  },
  {
    name: 'Hare',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 3,
    health: 4,
    abilityTrigger: 'Before Attack',
    tags: ['Perks'],
  },
  {
    name: 'Hatching Chick',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 2,
    health: 2,
    abilityTrigger: 'End Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Hoopoe Bird',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 3,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Disruption'],
  },
  {
    name: 'Owl',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 1,
    health: 2,
    abilityTrigger: 'Start Of Turn',
    tags: ['Cycle'],
  },
  {
    name: 'Pangolin',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 2,
    health: 5,
    abilityTrigger: 'Faint',
    tags: ['Toys'],
  },
  {
    name: 'Puppy',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Buy',
    tags: ['Toys'],
  },
  {
    name: 'Tropical Fish',
    imageSrc: '',
    pack: ['Puppy Pack'],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Anteater',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Capybara',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 2,
    health: 6,
    abilityTrigger: 'Roll & Sell',
    tags: ['Buffs'],
  },
  {
    name: 'Cardinal',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 4,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Perks'],
  },
  {
    name: 'Cassowary',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 5,
    health: 3,
    abilityTrigger: 'Friendly Gained Strawberry',
    tags: ['Strawberry'],
  },
  {
    name: 'Eel',
    imageSrc: '',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 3,
    attack: 4,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: [],
  },
  {
    name: 'Leech',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Hurt'],
  },
  {
    name: 'Okapi',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'Roll',
    tags: ['Rolling'],
  },
  {
    name: 'Orangutan',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 1,
    health: 4,
    abilityTrigger: 'End Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Pug',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 5,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Level-Up'],
  },
  {
    name: 'Roadrunner',
    imageSrc: '',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 3,
    attack: 4,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Strawberry'],
  },
  {
    name: 'Sage-Grouse',
    imageSrc: '',
    pack: ['Star Pack', 'Custom Pack'],
    tier: 3,
    attack: 2,
    health: 4,
    abilityTrigger: 'Friend Sold', // Sell Friend
    tags: ['Strawberry'],
  },
  {
    name: 'Toad',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Enemy Hurt',
    tags: ['Ailment'],
  },
  {
    name: 'Tuna',
    imageSrc: '',
    pack: ['Star Pack'],
    tier: 3,
    attack: 3,
    health: 5,
    abilityTrigger: 'Faint',
    tags: ['Hurt'],
  },
  {
    name: 'Baboon',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Buffs'],
  },
  {
    name: 'Betta Fish',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Faint'],
  },
  {
    name: 'Blue Dragon',
    imageSrc: '',
    pack: ['Golden Pack', 'Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 3,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tags: ['Mana', 'Trumpets'],
  },
  {
    name: 'Flea',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 3,
    health: 2,
    abilityTrigger: 'Faint',
    tags: ['Ailment'],
  },
  {
    name: 'Flying Fish',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 5,
    health: 2,
    abilityTrigger: 'Friend Summoned',
    tags: ['Summon'],
  },
  {
    name: 'Guineafowl',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'Hurt',
    tags: ['Trumpets', 'Hurt'],
  },
  {
    name: 'Jewel Caterpillar',
    imageSrc: '',
    pack: ['Golden Pack', 'Custom Pack'],
    tier: 3,
    attack: 1,
    health: 1,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Meerkat',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Gold'],
  },
  {
    name: 'Musk Ox',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 2,
    health: 4,
    abilityTrigger: 'Friend Ahead Faints',
    tags: ['Guard'],
  },
  {
    name: 'Osprey',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Patagonian Mara',
    imageSrc: '',
    pack: ['Golden Pack', 'Custom Pack'],
    tier: 3,
    attack: 2,
    health: 4,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Royal Flycatcher',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 2,
    health: 4,
    abilityTrigger: 'Enemy Summoned',
    tags: ['Disruption'],
  },
  {
    name: 'Surgeon Fish',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 4,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Trumpets'],
  },
  {
    name: 'Weasel',
    imageSrc: '',
    pack: ['Golden Pack'],
    tier: 3,
    attack: 3,
    health: 4,
    abilityTrigger: 'Faint',
    tags: ['Gold'],
  },
  {
    name: 'Axehandle Hound',
    imageSrc: '',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 4,
    health: 3,
    abilityTrigger: 'Before Attack',
    tags: ['Disruption'],
  },
  {
    name: 'Brain Cramp',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 1,
    health: 2,
    abilityTrigger: 'Empty Front Space',
    tags: ['Guard'],
  },
  {
    name: 'Caladrius',
    imageSrc: '',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 4,
    health: 3,
    abilityTrigger: 'Before Friend Attacks',
    tags: ['Mana'],
  },
  {
    name: 'Calygreyhound',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 4,
    health: 4,
    abilityTrigger: 'Faint',
    tags: ['Mana'],
  },
  {
    name: 'Deer Lord',
    imageSrc: '',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 4,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Faint'],
  },
  {
    name: 'Foo Dog',
    imageSrc: '',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 3,
    health: 5,
    abilityTrigger: 'Buy',
    tags: ['Buffs'],
  },
  {
    name: 'Fur-Bearing Trout',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 3,
    health: 5,
    abilityTrigger: 'Faint',
    tags: ['Mana', 'Perks'],
  },
  {
    name: 'Griffin',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 5,
    health: 4,
    abilityTrigger: 'Sell',
    tags: ['Toys'],
  },
  {
    name: 'Lucky Cat',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 2,
    health: 3,
    abilityTrigger: 'Level Up',
    tags: ['Level-Up', 'Gold'],
  },
  {
    name: 'Mana Hound',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 5,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Mana', 'Rolling'],
  },
  {
    name: 'Mandrake',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 4,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tags: ['Ailment'],
  },
  {
    name: 'Ouroboros',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 2,
    health: 4,
    abilityTrigger: 'Roll',
    tags: ['Rolling'],
  },
  {
    name: 'Skeleton Dog',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Faint'],
  },
  {
    name: 'Slime',
    imageSrc: '',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Faint',
    tags: ['Summon'],
  },
  {
    name: 'Tatzelwurm',
    imageSrc: '',
    pack: ['Unicorn Pack'],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'Friend Ahead Faints',
    tags: ['Guard'],
  },
  {
    name: 'Tree',
    imageSrc: '',
    pack: ['Unicorn Pack', 'Custom Pack'],
    tier: 3,
    attack: 2,
    health: 5,
    abilityTrigger: 'Start Of Battle',
    tags: ['Perks'],
  },
  {
    name: 'Dimetrodon',
    imageSrc: '',
    pack: ['Custom Pack'],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'Start Of Battle',
    tags: ['Cycle'],
  },
  {
    name: 'Great Potoo',
    imageSrc: '',
    pack: ['Custom Pack'],
    tier: 3,
    attack: 3,
    health: 3,
    abilityTrigger: 'Anyone Hurt',
    tags: ['Disruption'],
  },
  {
    name: 'Queen Bee',
    imageSrc: '',
    pack: ['Custom Pack'],
    tier: 3,
    attack: 2,
    health: 4,
    abilityTrigger: 'Bee Summoned',
    tags: [],
  },
  {
    name: 'Barnacle',
    imageSrc: '',
    pack: ['Custom Pack'],
    tier: 3,
    attack: 1,
    health: 3,
    abilityTrigger: 'End Turn',
    tags: ['Level-Up'],
  },
  {
    name: 'Centipede',
    imageSrc: '',
    pack: ['Custom Pack'],
    tier: 3,
    attack: 1,
    health: 4,
    abilityTrigger: 'Buy Friend', // Friend Bought
    tags: ['Cycle'],
  },
  {
    name: 'Gerenuk',
    imageSrc: '',
    pack: ['Custom Pack'],
    tier: 3,
    attack: 3,
    health: 4,
    abilityTrigger: 'Start Of Battle',
    tags: ['Disruption'],
  },
  //
  // --- TIER 4 ---
  //
] as const;

/*
{
  name: '',
  imageSrc: '',
  pack: [],
  tier: 4,
  attack: 0,
  health: 0,
  abilityTrigger: '',
  tags: []
},

*/

type PetsName = (typeof PETS_LIST)[number]['name'];
type PetsMapType = Record<PetsName, Pet>;

export const PETS_MAP = PETS_LIST.reduce((acc, pet) => {
  acc[pet.name] = pet;
  return acc;
}, {} as PetsMapType);
