import { Pet } from './types';

// 450 pets lol
export const Pets: Pet[] = [
  {
    name: 'Ant',
    imageSrc: 'https://superautopets.wiki.gg/images/5/56/Ant.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Faint',
    tag: ['Faint'],
  },
  {
    name: 'Beaver',
    imageSrc: 'https://superautopets.wiki.gg/images/2/26/Beaver.png',
    pack: ['Turtle Pack', 'Puppy Pack'],
    tier: 1,
    attack: 3,
    health: 2,
    abilityTrigger: 'Sell',
    tag: ['Cycle'],
  },
  {
    name: 'Cricket',
    imageSrc: 'https://superautopets.wiki.gg/images/3/3d/Cricket.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Faint',
    tag: ['Summon'],
  },
  {
    name: 'Duck',
    imageSrc: 'https://superautopets.wiki.gg/images/3/38/Duck.png',
    pack: ['Turtle Pack', 'Puppy Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Sell',
    tag: ['Buffs'],
  },
  {
    name: 'Fish',
    imageSrc: 'https://superautopets.wiki.gg/images/f/fb/Fish.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 3,
    abilityTrigger: 'Level Up',
    tag: ['Level-Up'],
  },
  {
    name: 'Horse',
    imageSrc: 'https://superautopets.wiki.gg/images/c/c3/Horse.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 1,
    abilityTrigger: 'Friend Summoned',
    tag: ['Summon'],
  },
  {
    name: 'Mosquito',
    imageSrc: 'https://superautopets.wiki.gg/images/8/8a/Mosquito.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 2,
    health: 2,
    abilityTrigger: 'Start Of Battle',
    tag: ['Disruption'],
  },
  {
    name: 'Otter',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9f/Otter.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 1,
    health: 3,
    abilityTrigger: 'Buy',
    tag: ['Cycle'],
  },
  {
    name: 'Pig',
    imageSrc: 'https://superautopets.wiki.gg/images/3/30/Pig.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 4,
    health: 1,
    abilityTrigger: 'Sell',
    tag: ['Gold', 'Cycle'],
  },
  {
    name: 'Pigeon',
    imageSrc: 'https://superautopets.wiki.gg/images/9/9e/Pigeon.png',
    pack: ['Turtle Pack'],
    tier: 1,
    attack: 3,
    health: 1,
    abilityTrigger: 'Sell',
    tag: ['Food'],
  },
];

/*
{
  name: '',
  imageSrc: '',
  pack: [''],
  tier: 1,
  attack: 0,
  health: 0,
  abilityTrigger: 'No Ability',
  tag: ['']
},

*/
